apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2022-02-28T11:47:31Z"
  name: $key1
  namespace: default
  resourceVersion: "4565570"
  uid: 1715423e-1d41-4430-bf22-c6c18b4682ef
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: $key1
  targetCPUUtilizationPercentage: 80
status:
  currentReplicas: 0
  desiredReplicas: 0
